### ISSUE TITLE
freebsd compile errror

### ISSUE THREAD

**Issue by stofel** [leo-project/erocksdb#29]
Hi
On freebsd 10 gcc48
As rebar3 debs, get compile error.
`g++ -fPIC -g -Wall -Werror -Wsign-compare -Wshadow -I. -I./include -std=c++11 -fPIC -DROCKSDB_PLATFORM_POSIX  -I /usr/home/alexs/work/ecolor/_build/default/lib/erocksdb/c_src/system/include -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DSNAPPY -DZLIB -DBZIP2 -DLZ4   -DHAVE_JEMALLOC -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -DNDEBUG -Woverloaded-virtual -Wnon-virtual-dtor -c db/builder.cc -o db/builder.o 
In file included from ./include/rocksdb/status.h:21:0,
                 from ./include/rocksdb/env.h:26,
                 from ./db/builder.h:10,
                 from db/builder.cc:10:
./include/rocksdb/slice.h: In member function 'std::string rocksdb::Slice::ToString(bool) const':
./include/rocksdb/slice.h:77:58: error: 'snprintf' was not declared in this scope
         snprintf(buf, 10, "%02X", (unsigned char)data_[i]);
`

But If 
~> cd _checkout/
~> git clone erocksdb
~> rebar compile
~> cd ../../
~> rebar release
Comiling is ok, but 

> erocksdb:open("test_db", [{create_if_missing, true}], []).
> {ok,<<>>}.
> Database Ref always <<>>

**Comment by benoitc** [comment]
yes this how a nif resource is returned. you can make sure it works by
running the tests.

**Comment by stofel** [comment]
Thanks. Tests work.

**Comment by mocchira** [comment]
Close as it worked.
