### ISSUE TITLE
What's the different between <<>> and rocksdb ref?

### ISSUE THREAD

**Issue by wudixiaotie** [leo-project/erocksdb#31]
Hi guys, I got confused about <<>> and rocksdb ref, my test code like this:
`(veronica1@10.20.0.68)1> {ok, Ref} = erocksdb:open("data/test.db", [{create_if_missing, true}], []).
{ok,<<>>}

(veronica1@10.20.0.68)2> Ref =:= <<>>.
true

(veronica1@10.20.0.68)6> erocksdb:get(Ref, <<"a">>, []).
{ok,<<"b">>}

(veronica1@10.20.0.68)6> erocksdb:get(<<>>, <<"a">>, []).
** exception error: bad argument
     in function  erocksdb:async_get/4
        called as erocksdb:async_get(#Ref<0.0.8.148>,<<>>,<<"a">>,[])
     in call from erocksdb:get/3 (/Users/tiexiao/code/my_projects/riak_core_x/_build/default/lib/erocksdb/src/erocksdb.erl, line 339)`

why the "Ref" equals <<>>, but use <<>> as db ref got error?
Any help?

**Comment by sumerman** [comment]
It's just the way Erlang represents opaque types that come from NIF. It doesn't mean though it's literally an empty binary.

**Comment by wudixiaotie** [comment]
@sumerman Thanks, Very helpful
