### ISSUE TITLE
Very slow compiling process

### ISSUE THREAD

**Issue by silviucpp** [leo-project/erocksdb#40]
Hello,

The native code compiles very very slow. Why you are not using for `make` the "-j" option to setup the concurrency for building ?

I mean instead doing `make` you are doing `make -j 12` and 12 threads will be using for compiling.

Silviu

**Comment by mocchira** [comment]
@silviucpp Yes you're right. I've done this with my patched build_deps.sh on my local machine and forgot to push into the github repo.

I'm going to push the commit later to fix the issue in more flexible way (determine the number of threads based on the number of CPU cores).

**Comment by mocchira** [comment]
@silviucpp https://github.com/leo-project/erocksdb/commit/b2e852c5a8466a3f01182545440d42f1c5e052bb I've pushed just now should solve the problem so can you try it out? if it works for you then please close the issue.

**Comment by silviucpp** [comment]
Fixed
