### ISSUE TITLE
Strange iterator behaviour

### ISSUE THREAD

**Issue by silviucpp** [leo-project/erocksdb#41]
Hello,

Having a db with the following keys: k1, k2, k3, k4.

```erl
{ok, It} = erocksdb:iterator(Ref, []),
 erocksdb:iterator_move(It, <<"k0">>).
```

Will return {ok,<<"k1">>,<<"value">>} instead invalid_iterator as I will expect .. k1 doesn't start with k0 ...

Silviu

**Comment by silviucpp** [comment]
hello guys any feedback on this ?

**Comment by mocchira** [comment]
@silviucpp sorry for the long delay. (I just missed it)

I'll look into this in my spare time and get back to you once I find something valuable for you.
