### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by benoitc** [leo-project/erocksdb#5]
I added the support of erocksd to [rkvs](https://github.com/refuge/rkvs) and for now it depends on the develop branch but it would be a lot better to rely on a tag. Do you plan to release it soon? What is missing right now?

**Comment by yosukehara** [comment]
Thank you for your comment.
We need to more test this library to find issues.
So we'll release this library on the master-branch after fixed all issues at middle of May.

**Comment by mocchira** [comment]
@benoitc We've released [0.4](https://github.com/leo-project/erocksdb/tree/0.4) the first stable version, 
so please use 0.4 in rkvs's dependencies. 
Thanks in advance.

**Comment by benoitc** [comment]
@mocchira thanks! just bumped rkvs to 0.2.1
