### ISSUE TITLE
is erocksdb used in production?

### ISSUE THREAD

**Issue by benoitc** [leo-project/erocksdb#8]
I was looking at the [leo_backend_db](https://github.com/leo-project/leo_backend_db.git) and I was suprised to not see erocksdb used there. Is erocksdb used in production somewhere? What is the current status?

**Comment by yosukehara** [comment]
Actually, `erocksdb` is included in [leo_backend_db 1.4-branch](https://github.com/leo-project/leo_backend_db/tree/1.4), which is a development branch because we need to more test it. We'll deliver the stable version of erocksdb with [LeoFS v1.4.0](https://github.com/leo-project/leofs/milestones).

**Comment by benoitc** [comment]
oh I didn't see it. Thanks for the info :)
